// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: v1_rpc_fetch_snippets.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchSnippetsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SnippetTopicId string `protobuf:"bytes,1,opt,name=snippet_topic_id,json=snippetTopicId,proto3" json:"snippet_topic_id,omitempty"`
}

func (x *FetchSnippetsRequest) Reset() {
	*x = FetchSnippetsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_rpc_fetch_snippets_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchSnippetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSnippetsRequest) ProtoMessage() {}

func (x *FetchSnippetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_rpc_fetch_snippets_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSnippetsRequest.ProtoReflect.Descriptor instead.
func (*FetchSnippetsRequest) Descriptor() ([]byte, []int) {
	return file_v1_rpc_fetch_snippets_proto_rawDescGZIP(), []int{0}
}

func (x *FetchSnippetsRequest) GetSnippetTopicId() string {
	if x != nil {
		return x.SnippetTopicId
	}
	return ""
}

type FetchSnippetsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Snippets []*Snippet `protobuf:"bytes,1,rep,name=snippets,proto3" json:"snippets,omitempty"`
}

func (x *FetchSnippetsReply) Reset() {
	*x = FetchSnippetsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_rpc_fetch_snippets_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchSnippetsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchSnippetsReply) ProtoMessage() {}

func (x *FetchSnippetsReply) ProtoReflect() protoreflect.Message {
	mi := &file_v1_rpc_fetch_snippets_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchSnippetsReply.ProtoReflect.Descriptor instead.
func (*FetchSnippetsReply) Descriptor() ([]byte, []int) {
	return file_v1_rpc_fetch_snippets_proto_rawDescGZIP(), []int{1}
}

func (x *FetchSnippetsReply) GetSnippets() []*Snippet {
	if x != nil {
		return x.Snippets
	}
	return nil
}

var File_v1_rpc_fetch_snippets_proto protoreflect.FileDescriptor

var file_v1_rpc_fetch_snippets_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x76, 0x31, 0x5f, 0x72, 0x70, 0x63, 0x5f, 0x66, 0x65, 0x74, 0x63, 0x68, 0x5f, 0x73,
	0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x76, 0x31, 0x5f, 0x73, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x40, 0x0a, 0x14, 0x46, 0x65, 0x74, 0x63, 0x68, 0x53,
	0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28,
	0x0a, 0x10, 0x73, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x5f, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x6e, 0x69, 0x70, 0x70, 0x65,
	0x74, 0x54, 0x6f, 0x70, 0x69, 0x63, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x12, 0x46, 0x65, 0x74, 0x63,
	0x68, 0x53, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2a,
	0x0a, 0x08, 0x73, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74,
	0x52, 0x08, 0x73, 0x6e, 0x69, 0x70, 0x70, 0x65, 0x74, 0x73, 0x42, 0x0f, 0x5a, 0x0d, 0x73, 0x77,
	0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_v1_rpc_fetch_snippets_proto_rawDescOnce sync.Once
	file_v1_rpc_fetch_snippets_proto_rawDescData = file_v1_rpc_fetch_snippets_proto_rawDesc
)

func file_v1_rpc_fetch_snippets_proto_rawDescGZIP() []byte {
	file_v1_rpc_fetch_snippets_proto_rawDescOnce.Do(func() {
		file_v1_rpc_fetch_snippets_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_rpc_fetch_snippets_proto_rawDescData)
	})
	return file_v1_rpc_fetch_snippets_proto_rawDescData
}

var file_v1_rpc_fetch_snippets_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_rpc_fetch_snippets_proto_goTypes = []interface{}{
	(*FetchSnippetsRequest)(nil), // 0: proto.FetchSnippetsRequest
	(*FetchSnippetsReply)(nil),   // 1: proto.FetchSnippetsReply
	(*Snippet)(nil),              // 2: proto.Snippet
}
var file_v1_rpc_fetch_snippets_proto_depIdxs = []int32{
	2, // 0: proto.FetchSnippetsReply.snippets:type_name -> proto.Snippet
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_rpc_fetch_snippets_proto_init() }
func file_v1_rpc_fetch_snippets_proto_init() {
	if File_v1_rpc_fetch_snippets_proto != nil {
		return
	}
	file_v1_snippet_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1_rpc_fetch_snippets_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchSnippetsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_rpc_fetch_snippets_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchSnippetsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_rpc_fetch_snippets_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_rpc_fetch_snippets_proto_goTypes,
		DependencyIndexes: file_v1_rpc_fetch_snippets_proto_depIdxs,
		MessageInfos:      file_v1_rpc_fetch_snippets_proto_msgTypes,
	}.Build()
	File_v1_rpc_fetch_snippets_proto = out.File
	file_v1_rpc_fetch_snippets_proto_rawDesc = nil
	file_v1_rpc_fetch_snippets_proto_goTypes = nil
	file_v1_rpc_fetch_snippets_proto_depIdxs = nil
}
